# Multiple app config
DEVELOPMENT: &dev
    APP_NAME: 'heracles'
    APP_TYPE: 'app'
    APP_BASE: 'bottle'
    MODULE: 'heracles:app'
    CLIENT_ID: 7131
    CLIENT_SECRET: '55df5dde98eb34acb6b0b306a0b200fa'
    DEBUG: true

    CONTENT_PATH: 'templates/'

STAGING:
    <<: *dev

PRODUCTION:
    <<: *dev
    DEBUG: false
    MAIL_DEBUG: false
